# Generated by Django 3.1 on 2020-10-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
