version: '3.0'

services:
  web:
    build: .
    command: bash -c './wait-for.sh postgres:5432 -- ./cmd.sh'
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - app-env.env
    restart: always
    networks:
      - local
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ~/.docker_db_data/postgres:/var/lib/postgresql/data
    env_file:
      - app-env.env
    restart: always
    networks:
      - local
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - local
    depends_on:
      - web

networks:
  local:
    driver: bridge
