# Generated by Django 3.1 on 2020-09-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.TextField(default=None),
        ),
    ]
